language: ruby
cache: bundler

sudo: false

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7

gemfile:
  - gemfiles/ar_5_1.gemfile
  - gemfiles/ar_5_0.gemfile
  - gemfiles/ar_4_2.gemfile

before_script:
  - bundle exec rake -f spec/dummy/Rakefile db:schema:load
